package com.melaniadev.fitcare.ui

fun mockList(): List<Customer> {
    val customersList = listOf(
        Customer("0Bernat", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.MALE, "37", null, null, null, null, null, null),
        Customer("1Mel", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("2Marina", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("3Estela", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("4Nadine", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("5riel", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.MALE, "37", null, null, null, null, null, null),
        Customer("6Bernat", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.MALE, "37", null, null, null, null, null, null),
        Customer("7Mel", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("8Marina", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("9Estela", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("10Nadine", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("11Ariel", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.MALE, "37", null, null, null, null, null, null),
        Customer("12Bernat", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.MALE, "37", null, null, null, null, null, null),
        Customer("13Mel", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("14Marina", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("15Estela", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("16Nadine", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("17Ariel", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.MALE, "37", null, null, null, null, null, null),
        Customer("18Bernat", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.MALE, "37", null, null, null, null, null, null),
        Customer("19Mel", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("20Marina", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("21Estela", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("22Nadine", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("23Ariel", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.MALE, "37", null, null, null, null, null, null),
        Customer("24Bernat", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.MALE, "37", null, null, null, null, null, null),
        Customer("25Mel", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("26Marina", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("27Estela", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("28Nadine", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("29Ariel", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.MALE, "37", null, null, null, null, null, null),
        Customer("30Bernat", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.MALE, "37", null, null, null, null, null, null),
        Customer("31Mel", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("32Marina", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("33Estela", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("34Nadine", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.FEMALE, "37", null, null, null, null, null, null),
        Customer("35Ariel", "25/03/23", "07/05/24", Professional("Marco Aurelio", Therapy.PHYSICAL, null), Gender.MALE, "37", null, null, null, null, null, null),
        )
    return customersList
}
